### ISSUE TITLE
Link when add sheet to Roll20 game points to wrong page

### ISSUE THREAD

**Issue by Jimwaters** [MadCoder253/roll20-character-sheets#13] opened 2018-05-30 16:07 UTC
When adding this sheet to a game I see the following, but the link is a dead one.  Should point to https://github.com/MadCoder253/roll20-character-sheets/blob/master/GURPS/script.js

:-

```
GURPS

Authors:Devindra Payment (@Ardnived), Joseph Mason (@sdJasper), Ken Foubert (@MadCoder)

If you are a mentor, you can use this script to automatically determine success and failure. https://raw.githubusercontent.com/Ardnived/Roll20-GURPS-Sheet/master/GURPS/script.js


```

**Comment by KlingonMike** [comment] 2018-07-26 12:33
Most likely going to remove this URL all together because this particular user, MadCoder253, is not responding and therefore not providing any updates.

**Comment by KlingonMike** [comment] 2018-07-28 02:46
Pull request to be made 8/01/2018 in version 1.3.7

**Comment by KlingonMike** [comment] 2018-07-31 20:07
Confirmed this has been changed after PULL. You may close this issue.

**Closed** 2019-03-06 06:54 UTC
